### ISSUE TITLE
服务器

### ISSUE THREAD

**Issue by ljxzhuce123** [mk43/ZZChat#1]
您好，服务器端不会弄，能将完整的工程上传吗，或者教教我怎么弄服务器，谢谢！

**Comment by mk43** [comment]
你好，这里上传的服务端就是所有代码，其它的只是eclipse生成的代码和一些库。
如果你对服务器或网络通讯不熟，可以先看看java的socket。这里推荐mooc【http://www.imooc.com/learn/161】。
然后自己找点socket的小例子实现以下就懂了。希望对你有帮助。

**Comment by ljxzhuce123** [comment]
好的，非常感谢！

**Comment by mk43** [comment]
恩，也谢谢你的支持
